package component;

import utility.Grouper;
import utility.TO;

import java.util.ArrayList;

/// Class instances relate a phone-number to a person.
public class PhoneNumber implements ICSV
{
    private int _personID; // personID is generated by RoskildeHaveID, and will uniquely identify a person
    private String _phoneNumber; // phone number; its a String to take international numbers into account
    private String _comment; // phone#s often have comments attached

    public PhoneNumber(String phoneNumber, int personID, String comment)
    {
        _personID = personID;
        _phoneNumber = phoneNumber;
        _comment = comment;
    }

    public static PhoneNumber fromCSV(String csvString)
    {
        ArrayList<String> csvList = Grouper.splitStringAsCSV(csvString, ",", 3);
        PhoneNumber result = null;

        try
        {
            int personID = Integer.parseInt(csvList.get(0));
            String phoneNumber = csvList.get(1);
            String comment = csvList.get(2);

            result = new PhoneNumber(phoneNumber, personID, comment);

        } catch(Exception e)
        {
            System.out.println("Bad data formatting in supplied PhoneNumber csv String\n" +
                               TO.yellow(e.getMessage()));
            result = returnEmptyPhoneNumberEntry();
        }

        return result;
    }

    public static PhoneNumber returnEmptyPhoneNumberEntry()
    {
        return new PhoneNumber("10000000", -1,
                               "Dårlig data. Kontakt systemadministratoren");
    }

    @Override
    public String toCSV()
    {
        return _personID + "," + _phoneNumber + "," + _comment;
    }

    public String getPhoneNumber(){ return _phoneNumber; }

    public void setPhoneNumber(String phoneNumber){ this._phoneNumber = phoneNumber; }

    public int getPersonID(){ return _personID; }

    public void setPersonID(int personID){ this._personID = personID; }

    public void setPersonID(Person person){ _personID = person.getID(); }

    public String getComment(){ return _comment; }

    public void setComment(String comment){ this._comment = comment; }


}
